### PR TITLE
Update publications.yml

### PR DESCRIPTION
**Pull request by ranbenbasat**
Added an entry for our ICNP paper. Will update URL once it becomes available on IEEE Xplore.

### CODE REVIEW

**Comment by ranbenbasat** [comment]
Sure, thanks.

**Comment by jnfoster** [comment]
Now that ICNP is done, do you want to update this PR so we can merge it?

**Comment by ranbenbasat** [comment]
Sure, updated it here.

**Comment by jnfoster** [comment]
Would you mind also rebasing on master and resolving the conflicts?

**Comment by ranbenbasat** [comment]
Hi, sorry, I'm not too familiar with GitHub. It now shows that there are no conflicts with the base branch. Was that you meant?

**Pull request merged**
