### PR TITLE
added switchpointer paper 

### PR DESCRIPTION
**Pull request by PraveenTammana**

### CODE REVIEW

**Comment by jnfoster** [comment]
Okay, thanks for the clarification and edit.

**Comment by jnfoster** [comment]
One more small nit: could you please change the URL so it points to the PDF?

**Comment by jnfoster** [comment]
Sorry to be so picky, but I'm trying to keep things consistent so we don't end up with the usual BibTeX mess :-)

**Comment by PraveenTammana** [comment]
No problem. I can understand. I should have done it earlier.

**Pull request merged**
